### PR TITLE
Use BinaryProvider-wrapped GR binaries

### PR DESCRIPTION
**Pull request by staticfloat**
This uses BinaryProvider-wrapped GR binaries, built within Yggdrasil.  All [the BB script](https://github.com/JuliaPackaging/Yggdrasil/blob/ecc0f872960f50da677c3a2dc1bce34adce8e78a/GR/build_tarballs.jl) does is re-arrange the [official binaries](https://github.com/sciapp/gr/releases/tag/v0.39.0) to be more uniform and conformant to what we expect in the Julia world.

### CODE REVIEW

**Comment by tanmaykm** [comment]
Bump! It will be great to have this rebased and merged.

**Comment by jheinen** [comment]
Thank you for the PR. Unfortunately, I can't merge it as we would loose some basic functionality:

- GR could no longer be installed in a common folder (for multi-user environments, e.g. an NFS-mounted /usr/local filesystem) or in Docker images
- the QML part would be broken
- the different GR run-time distributions (for Debian, Ubuntu, ArchLinux, CentOS, SuSE) are not used

**Comment by staticfloat** [comment]
Thanks @jheinen, thanks for the response.

> * GR could no longer be installed in a common folder (for multi-user environments, e.g. an NFS-mounted /usr/local filesystem) or in Docker images

Do you mean by this that you want to preserve the current "search `/opt`, `/usr/local`, `/usr`" behavior, or do you mean something else?

> * the QML part would be broken

Can you explain what needs to be done to un-break this?  I see in your current `build.jl` there are some conditional steps taken in order to hook into `Qt`; it looks to me like this code could be included in the `build.jl` proposed within this PR.  Is that all that needs to happen, or does something need to change in the binaries that are being downloaded.

> * the different GR run-time distributions (for Debian, Ubuntu, ArchLinux, CentOS, SuSE) are not used

Can you explain the differences between the different tarballs?  Since these are all `glibc`-based distributions, what is distribution-specific?

Thank you!

**Comment by FlorianRhiem** [comment]
> Can you explain the differences between the different tarballs? Since these are all glibc-based distributions, what is distribution-specific?

We try to minimize the dependencies to the system itself, but for the applications or UI-based plugins, some dependencies like Qt and X11 cannot be avoided. As the versions of those libraries and how they are handled can vary greatly between distributions, we had to add more and more binaries to make sure they will work on users' systems.

**Comment by jheinen** [comment]
- Yes, the search for `/opt, /usr, /usr/local` should be preserved. A single GR distribution can then be used for different languages (Python, Julia, C - which is often the case in our environments) and/or by different users.

- The QML sections should be preserved, too. The modification of the shared object is required on macOS.

- It turned out, that using a single distribution for different Linux flavours leads to problems, ranging from undefined run-time behaviour to segmentation faults (in certain situations). That's why we set up a complex CI/CD server and build dedicated distributions for the most popular Linux distributions. Alternatively, one could re-distribute critical parts of the system run-time - that's how the problem is often solved in commercial tools - but this leads to huge tar balls and duplicates on the target systems.

**Comment by ViralBShah** [comment]
It would be great to take this PR all the way. It seems that what we need is to see if a system provided GR is available, and fallback to BinaryProvider only if it is not. Is that right?

**Comment by ViralBShah** [comment]
I guess this will have to be migrated to the Artifacts system in order to go ahead, while retaining all the things @jheinen mentions above. I am hoping that the two are not incompatible.

**Comment by KristofferC** [comment]
Can this be opt-in or something. Not having this means e.g. GR (Plots) doesn't work well with e.g. PackageCompiler.jl apps.

**Comment by ViralBShah** [comment]
I think proper BinaryBuilder builds of GR are in progress. I think this PR can be closed.

**Comment by ViralBShah** [comment]
I think this one can be closed.

**Comment by ViralBShah** [comment]
Probably close this one?

**Pull request closed without merging**
