### PR TITLE
Use GR_jll for GR binaries

### PR DESCRIPTION
**Pull request by barche**
This is related to https://github.com/JuliaPackaging/Yggdrasil/pull/1506

The changes are:
* Use GR_jll binaries
* Use gksqt and restart it from Julia if needed
* Bump Julia requirement to 1.3, needed for GR_jll artifacts.

To test, first add the unreleased GR_jll in Pkg mode:
```
add https://github.com/barche/GR_jll.jl.git
```

This can only be merged after https://github.com/JuliaPackaging/Yggdrasil/pull/1506 is ready for all platforms and merged.

Please test carefully, I only tried it on Mac ;)

### CODE REVIEW

**Comment by barche** [comment]
The original version didn't work if the windows was closed when using Plots.jl, so I refactored it a bit. Now tested on Mac, Windows and Linux, works standalone and with QML.jl.

**Comment by jheinen** [comment]
@barche : Thanks for the PR.

I tried to integrate it in a way, that both the BB libraries and the current run-time libraries can be used. I tried things like:

```julia
if Base.find_package("GR_jll") == nothing
    grdir = joinpath(dirname(@__FILE__), "..", "deps", "gr")
    if os == :Windows
        libGR = "libGR.dll"
        libGR3 = "libGR3.dll"
        libGRM = "libGRM.dll"
    else
        libGR = "libGR.so"
        libGR3 = "libGR3.so"
        libGRM = "libGRM.so"
     end
else
    @eval import GR_jll
    grdir  = dirname(dirname(GR_jll.libGR_path))
    libGR  = GR_jll.libGR
    libGR3 = GR_jll.libGR3
    libGRM = GR_jll.libGRM
    GR_jll.gksqt(gkscmd -> GR_jll.run(`gksqt`; wait=false))
    ENV["GKS_QT"] = ""
end
```

This doesn't work, because the `ccall` (:function, "library") pair be literal constants. Other attempts ended in World Age problems.

Do you have any idea, how to come around this?

Completely "switching" to BinaryBuilder would break several things in our environment ...

**Comment by barche** [comment]
The easiest way to use a libGR different from the one supplied by BinaryBuilder would be to set up an [`Overrides.toml`](https://julialang.github.io/Pkg.jl/dev/artifacts/#Overriding-artifact-locations-1) file, using an approach similar to what is described here for libcxxwrap: https://github.com/JuliaInterop/libcxxwrap-julia#using-the-compiled-libcxxwrap-julia-in-cxxwrap

**Comment by maleadt** [comment]
> the `ccall` (:function, "library") pair must be literal constants

That's something that will change in 1.6, but for now you can use `@runtime_ccall` from LLVM.jl: https://github.com/maleadt/LLVM.jl/blob/c447e61110373502d640335ac89ae971cd844279/src/util.jl#L70-L113

**Comment by ViralBShah** [comment]
@staticfloat - Is what was done for the MPI packages an alternate approach to opt out of the artifacts?

**Comment by staticfloat** [comment]
The "standard" way to do this right now is to have your `deps/build.jl` generate a `.jl` file that is then `include()`'ed by your package.  I'm not a huge fan of this approach as it means that your `deps/` folder has state that can get stale and then break, but due to the ccall limitations (that we are overcoming in 1.6! Huzzah!) it's probably the easiest solution.  `FFTW.jl` [showcases the method](https://github.com/JuliaMath/FFTW.jl/blob/master/deps/build.jl) pretty nicely.

**Comment by jheinen** [comment]
> The "standard" way to do this right now is to have your `deps/build.jl` generate a `.jl` file that is then `include()`'ed by your package. I'm not a huge fan of this approach as it means that your `deps/` folder has state that can get stale and then break, but due to the ccall limitations (that we are overcoming in 1.6! Huzzah!) it's probably the easiest solution. `FFTW.jl` [showcases the method](https://github.com/JuliaMath/FFTW.jl/blob/master/deps/build.jl) pretty nicely.

That looks to me like a reasonable solution. I'll try this tomorrow ...

**Comment by barche** [comment]
Just to be clear: Is the requirement to have the current automatic download from `build.jl` operational, or do you need GR to work for people who have the GR binaries installed already?

**Comment by jheinen** [comment]
> Just to be clear: Is the requirement to have the current automatic download from `build.jl` operational, or do you need GR to work for people who have the GR binaries installed already?

Both. I hope, @staticfloat 's solution will work for us ...

**Comment by ViralBShah** [comment]
Just checking if anyone can help to get this PR merged and a new release tagged.

**Comment by jheinen** [comment]
I made a lot of tests (using macOS 10.16) and it seems to me, that we have to start `gksqt` from within GR. Starting `gksqt` from Julia often causes the session to hang up.

Q: Is there a way to obtain the required environment (with library paths) to start `gksqt` ?

**Comment by barche** [comment]
> Q: Is there a way to obtain the required environment (with library paths) to start `gksqt` ?

This gets the two relevant variables:

```julia
gksqt() do x
    return ENV["DYLD_FALLBACK_LIBRARY_PATH"], ENV["PATH"]
end
```

**Comment by staticfloat** [comment]
There's a more direct (and, it so happens, threadsafe!) way of doing that:

```
using GR_jll
GR_jll.LIBPATH
GR_jll.PATH
```

The reason that calling the `gksqt()` function is thread-unsafe is that it uses `withenv(...)` which itself calls `setenv()` [which is thread-unsafe on many libc's](https://blogs.gnome.org/mcatanzaro/2018/02/28/on-setenv-and-explosions/).  Before Julia v1.6, we didn't have a good way to pass default environment variables to sub-processes, so we just hoped that people generally wouldn't run into this issue, but as multithreading becomes more and more common it's important to eliminate as many uses of `setenv()` and `getenv()` as possible.  Julia 1.6+ will support a simpler way to call executables from JLLs which won't involve calling `setenv()`.

**Comment by jheinen** [comment]
Great! Works fine for macOS (except the `GKS QtTerm` icon doesn't show up). See [this](https://github.com/jheinen/GR.jl/commit/cf2cc83df0ca33aa4de2e519850eab8c57481a1d) commit.

Should also work for Linux - not sure about Windows ... Can check this on Monday.

**Comment by barche** [comment]
> Should also work for Linux - not sure about Windows ... Can check this on Monday.

I just tested using the BinaryBuilder provider and it appears to work, but you need to add GR_jll to Project.toml (preferably with a compat entry I guess).

**Comment by VPetukhov** [comment]
Hi @jheinen,
Is there something preventinf this PR from being merged? Having binary dependencies would be really great!

**Comment by zsz00** [comment]
Hi @jheinen,
Is there something preventinf this PR from being merged?

**Comment by VPetukhov** [comment]
To have it in one place, here is the answer from jheinen on gitter:

> You can set ENV["JULIA_GR_PROVIDER"] = "BinaryBuilder" (in GR#master), but there are still some [issues](https://github.com/jheinen/GR.jl/issues/314#issuecomment-712629447).

**Comment by ViralBShah** [comment]
I think this PR can be closed and we should probably open new issues as necessary. Now that GR 0.53 is out and we have the environment variable, we can prepare everything else in the rest of the ecosystem.

**Comment by ViralBShah** [comment]
close?

**Pull request closed without merging**
