### PR TITLE
Depend on GRCore_jll instead of GR_jll

### PR DESCRIPTION
**Pull request by barche**
The purpose of this PR is to make the dependency on Qt5 optional, and give the user a choice between Qt5 and Qt6. The reason for this is that Qt5 and Qt6 can't be loaded at the same time in a Julia environment, so giving the user a choice can help in avoiding conflicts. Furthermore, GR is often used in the context of notebooks, where no Qt window is required at all, and this change saves about 100 MB of disk space and a few tens of MB download.

To make this possible, the GR_jll package will be split into `GRCore_jll`, `QRQt5_jll` and `GRQt6_jll`. Here, the `GRCore_jll` package does not depend on Qt, while the Qt dependencies are built into the two GRQt packages. The Qt packages are introduced as weak dependencies in Julia 1.9, or loaded using `Requires.jl` on earlier Julia versions.

This is a draft PR to show how I think this could be implemented, and to check that this change would be acceptable for the community.

To test it, start from a clean Julia depot (using the `JULIA_DEPOT_PATH` environment variable) and then, in Julia pkg mode:

```
status
registry add https://github.com/barche/CxxWrapTestRegistry.git
add https://github.com/barche/GR.jl.git#grcore-jll
add GRQt5_jll
```

Then, when plotting in a notebook this should work after just doing `using GR`, but getting a plot window from the command line requires `using GR, GRQt5_jll`.

See https://github.com/JuliaPackaging/Yggdrasil/pull/6751 and https://github.com/JuliaPackaging/Yggdrasil/pull/6752 for the proposed changes in Yggdrasil

### CODE REVIEW

**Comment by jheinen** [comment]
First of all thanks for the MR.

Unfortunately, the above steps to test the new packages didn't work for me - I'm on an Intel Mac with Julia 1.9.0. After install the packages I get:
```julia
using GR, GRQt5_jll
┌ Error: Error during loading of extension GRQt5Ext of GR, use `Base.retry_load_extensions()` to retry.
```

In principle, I would not be opposed to splitting the GR package. However, many users will not like the fact that the Qt5 or Qt6 part has to be imported explicitly. Couldn't this import be automated, depending on the environment (`GKS_WSTYPE`)?

**Comment by barche** [comment]
I forgot to actually add a necessary change for Julia 1.9, that should be fixed now. I have made an attempt to automate adding and importing `GRQt5_jll`, but I'm not sure how safe this is since it relies on calling `@eval`. Maybe automating the call to `Pkg.add` is also overkill, would it be acceptable to require users to manually install GRQt5_jll (or later GRQt6_jll)?

Also, I just noticed Windows is broken, so more fixes are needed for sure :)

**Comment by barche** [comment]
Windows error is fixed, though for some reason I don't understand this require copying the Qt dlls into the GR scratchspace, even though all paths are set as they should be.

Also, I think adding the GRQt5 pacjage automatically in `init` was a bit overkill, so now it is just loaded if available, and otherwise a warning asking to add the `GRQt5_jll` or `GRQt6_jll` package is shown. So for plotting in the REPL the only breaking change is that users must do `add GRQt5_jll`, importing it explicitly is not needed.

**Comment by jheinen** [comment]
I think we have to update https://github.com/JuliaPackaging/Yggdrasil/pull/6751 and https://github.com/JuliaPackaging/Yggdrasil/pull/6752 first - I'd do so, but I have no access.

**Comment by barche** [comment]
Done, I updated both Yggdrasil PRs. I think that the Yggdrasil PRs can be merged, that way CI here should also run correctly once the JLLs are in the registry.

**Comment by barche** [comment]
@jheinen If you have no objections I'll merge https://github.com/JuliaPackaging/Yggdrasil/pull/6751 and https://github.com/JuliaPackaging/Yggdrasil/pull/6752 so we can test this further? Both are at GR version 0.72.7.

**Comment by jheinen** [comment]
I am surprised that the `eval` part does not bother anyone. I thought that would have been the k.o. criterion for precompilation.

If no one objects, feel free to merge. The packages can be maintained in parallel for a while, right?

**Comment by jheinen** [comment]
Thanks, this works fine with Julia 1.9.1 and Qt5 (`JULIA_DEPOT_PATH=${HOME}/tmpdepot julia`)
```
registry add https://github.com/barche/CxxWrapTestRegistry.git
add https://github.com/barche/GR.jl.git#grcore-jll
add GRQt5_jll
```
Will QML#main be supported (once GRQt6_jll) is available?
```
registry add https://github.com/barche/CxxWrapTestRegistry.git
add https://github.com/barche/GR.jl.git#grcore-jll
add QML#main
```
Right now, it fails with
```
Failed to precompile QML [2db162a6-7e43-52c3-8d84-290c1c42d82a] to "/Users/jheinen/tmpdepot/compiled/v1.10/QML/jl_3BBUGn".
C++ exception while wrapping module QML: invalid subtyping in definition of QObject with supertype Any
```

**Comment by barche** [comment]
Yes, QML and its Qt6 dependency is the reason I looked into this. I wonder how to proceed regarding Julia 1.6 support, it would not be too hard to eliminate the JLLPrefixes dependency (which requires Julia 1.8) I guess.

I don't think there is much to gain in splitting up GR itself, it precompiles and loads pretty quickly as it is. If we want to slim down further we could make GRCore_jll smaller, e.g. by not including Cairo and/or FFMPEG by default, but I'm not sure the gains (maybe 100 MB install size) are worth the extra complexity (require users to manually add a GRCairo_jll and GRFFMPEG_jll package, and maintain those of course).

**Comment by barche** [comment]
This now passes on Julia 1.6 as well, but I still need to add Qt6 support before this can be considered ready.

**Comment by mkitti** [comment]
Is this ready now that QT 6 is available?

**Comment by barche** [comment]
I still need to commit the changes needed here for Qt6, and I'd also like to test if a separate extension module is needed to enable Wayland through the JLL.

Once that is done, we need to check how this affects Plots.jl, since as it stands merging this would result in users needing to install one of the GRQT jll packages manually before a plot window is available, so this has an impact on the workflow from the Julia REPL.

**Comment by barche** [comment]
With this PR and the new `Qt6Wayland_jll` it is now also possible to use Wayland for the GR plot window:

```julia
using GR, GRQt6_jll, Qt6Wayland_jll
plot(rand(4,4))
```

However, this is actually because in that case, a `gksqt` compiled against Qt6 is used, and `Qt6Wayland` is compatible with the BinaryBuilder system (unlike the Qt5 variant, which I could never get to compile).

I am now questioning the approach of this PR and wondering if it will not be too disruptive (need to manually `add GRQt6_jll` or `add GRQt5_jll` to get a plot window) to the Plots ecosystem for only a small benefit (smaller download and less disk usage in case of notebook usage). A second benefit I saw, namely avoiding conflict between Qt5 and Qt6 seems academic, since the only other package depending on Qt5 is OpenCV.jl.

In the end, I think it would be better to just rebuild `GR_jll` against Qt6, then we get the Wayland functionality and everything will just keep working transparently for everyone. If there are conflicts with OpenCV we can convert that to Qt6 too.

**Comment by barche** [comment]
Closing this, see #524

**Pull request closed without merging**
