### PR TITLE
Using Libdl.dlsym to dynamically load function pointers

### PR DESCRIPTION
**Pull request by mkitti**
This version uses `Libdl.dlsym` to load function pointers from library handles set in `__init__`. If `GR_jll` is loaded, then this will use the handles that it loaded.

The library handles are constant references to a `Ptr{Nothing}`. This version should work in Julia 1.5 and Julia 1.6.

An added benefit is that GR can be immediately used after rebuilding. The Julia session does not need to be restarted.

By the third cold execution of GR, things should be relatively fast.
```julia
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time begin
           using GR
           x = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
           y = [0.3, 0.5, 0.4, 0.2, 0.6, 0.7]
           @time GR.polyline(x,y)
           @time GR.axes(0.2, 0.2, 0, 0, 1, 1, -0.01)
           @time GR.updatews()
       end
[ Info: Precompiling GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71]
Your GR installation is incomplete. Rerunning build step for GR package.
   Building GR → `~/.julia/dev/GR/deps/build.log`
[ Info: GR was successfully rebuilt
  0.316400 seconds (30.14 k allocations: 1.562 MiB)
  0.016258 seconds (27.92 k allocations: 1.458 MiB)
  0.011584 seconds (18.45 k allocations: 1.014 MiB)
 12.061675 seconds (16.11 M allocations: 905.907 MiB, 4.76% gc time)

julia> exit()
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time begin
           using GR
           x = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
           y = [0.3, 0.5, 0.4, 0.2, 0.6, 0.7]
           @time GR.polyline(x,y)
           @time GR.axes(0.2, 0.2, 0, 0, 1, 1, -0.01)
           @time GR.updatews()
       end
[ Info: Precompiling GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71]
  0.316459 seconds (30.14 k allocations: 1.562 MiB)
  0.017401 seconds (27.92 k allocations: 1.458 MiB)
  0.012289 seconds (18.45 k allocations: 1.014 MiB)
 12.998196 seconds (7.39 M allocations: 424.382 MiB, 1.50% gc time)

julia> exit()
$ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.1 (2020-08-25)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time begin
           using GR
           x = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
           y = [0.3, 0.5, 0.4, 0.2, 0.6, 0.7]
           @time GR.polyline(x,y)
           @time GR.axes(0.2, 0.2, 0, 0, 1, 1, -0.01)
           @time GR.updatews()
       end
  0.317188 seconds (30.14 k allocations: 1.562 MiB)
  0.016998 seconds (27.92 k allocations: 1.458 MiB)
  0.116907 seconds (18.45 k allocations: 1.014 MiB, 89.19% gc time)
  5.720824 seconds (6.76 M allocations: 395.635 MiB, 3.76% gc time)

```

For Julia 1.6.0, this goes very quickly:
```julia
$ julia-1.6.0/bin/julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time begin
           using GR
           x = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
           y = [0.3, 0.5, 0.4, 0.2, 0.6, 0.7]
           @time GR.polyline(x,y)
           @time GR.axes(0.2, 0.2, 0, 0, 1, 1, -0.01)
           @time GR.updatews()
       end
[ Info: Precompiling GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71]
Your GR installation is incomplete. Rerunning build step for GR package.
    Building GR → `~/.julia/dev/GR/deps/build.log`
Precompiling project...
  Progress [========================================>]  2/2
  ? Plots
1 dependency successfully precompiled in 14 seconds (119 already precompiled)
1 dependency failed but may be precompilable after restarting julia
[ Info: GR was successfully rebuilt
  0.315271 seconds (28.65 k allocations: 1.719 MiB, 6.64% compilation time)
  0.044981 seconds (24.23 k allocations: 1.500 MiB, 51.01% gc time, 99.28% compilation time)
  0.012205 seconds (18.39 k allocations: 1.163 MiB, 99.15% compilation time)
 20.081061 seconds (9.05 M allocations: 552.740 MiB, 1.65% gc time, 4.57% compilation time)

julia> exit()
$ julia-1.6.0/bin/julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time begin
           using GR
           x = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
           y = [0.3, 0.5, 0.4, 0.2, 0.6, 0.7]
           @time GR.polyline(x,y)
           @time GR.axes(0.2, 0.2, 0, 0, 1, 1, -0.01)
           @time GR.updatews()
       end
[ Info: Precompiling GR [28b8d3ca-fb5f-59d9-8090-bfdbd6d07a71]
  0.315480 seconds (28.65 k allocations: 1.719 MiB, 6.84% compilation time)
  0.019071 seconds (24.23 k allocations: 1.500 MiB, 98.97% compilation time)
  0.010915 seconds (18.39 k allocations: 1.163 MiB, 99.04% compilation time)
  3.518684 seconds (1.92 M allocations: 117.392 MiB, 1.31% gc time, 25.71% compilation time)

julia> exit()
$ julia-1.6.0/bin/julia 
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.6.0 (2021-03-24)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> @time begin
           using GR
           x = [0, 0.2, 0.4, 0.6, 0.8, 1.0]
           y = [0.3, 0.5, 0.4, 0.2, 0.6, 0.7]
           @time GR.polyline(x,y)
           @time GR.axes(0.2, 0.2, 0, 0, 1, 1, -0.01)
           @time GR.updatews()
       end
  0.315370 seconds (28.65 k allocations: 1.719 MiB, 7.17% compilation time)
  0.019048 seconds (24.23 k allocations: 1.500 MiB, 98.91% compilation time)
  0.011118 seconds (18.39 k allocations: 1.163 MiB, 98.85% compilation time)
  0.774020 seconds (430.62 k allocations: 30.746 MiB, 2.92% gc time, 7.44% compilation time)
```

### CODE REVIEW

**Comment by mkitti** [comment]
Looks like I forgot to import Libdl into gr3.

**Comment by mkitti** [comment]
@jheinen I added a feature such that the package will fallback to the GR provider method if deps.jl (GR_jll) fails. I alerted the BinaryBuilder folks about the Qt5Base_jll on Mac.

We might want to remove one of the Travis environmental variable settings so the Travis matrix is not so huge.

**Review by jheinen — COMMENTED** [review]
What's the error message on Windows?

**Comment by mkitti** [comment]
```
julia> using GR
Your GR installation is incomplete. Rerunning build step for GR package.
    Building GR → `C:\Users\kittisopikulm\.julia\scratchspaces\44cfe95a-1eb2-52ea-b672-e2afdf69b78f\74c7dcd49c41674bd864db138fef48213bc56639\build.log`
ERROR: InitError: IOError: open("C:\\Users\\kittisopikulm\\.julia\\packages\\GR\\HpNnL\\src\\GR.jl", 257, 438): permission denied (EACCES)
Stacktrace:
  [1] uv_error
    @ .\libuv.jl:97 [inlined]
  [2] open(path::String, flags::UInt16, mode::UInt16)
    @ Base.Filesystem .\filesystem.jl:87
  [3] touch(path::String)
    @ Base.Filesystem .\file.jl:426
  [4] top-level scope
    @ ~\.julia\packages\GR\HpNnL\src\GR.jl:290
  [5] eval
    @ .\boot.jl:360 [inlined]
  [6] __init__()
    @ GR ~\.julia\packages\GR\HpNnL\src\GR.jl:286
  [7] _include_from_serialized(path::String, depmods::Vector{Any})
    @ Base .\loading.jl:674
  [8] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String)
    @ Base .\loading.jl:760
  [9] _require(pkg::Base.PkgId)
    @ Base .\loading.jl:998
 [10] require(uuidkey::Base.PkgId)
    @ Base .\loading.jl:914
 [11] require(into::Module, mod::Symbol)
    @ Base .\loading.jl:901
during initialization of module GR
```

**Comment by jheinen** [comment]
"touch"img parts of the packages is probably not a good idea for shared installations, where the users typically have no write access to the package directories.

Nevertheless, thanks a lot for your MRs. They will solve many problems that have been described in the last few days.

👍 💯 👏

**Comment by mkitti** [comment]
The purpose was to make sure that GR.jl recompiles itself. It was not before since deps.jl was not included earlier.

Now deps.jl is always included and is just a blank file when the GR binary provider is used. If deps.jl is changed, GR.jl should recompile now.

**Pull request merged**
