### PR TITLE
precompile: only call when generating output

### PR DESCRIPTION
**Pull request by sjkelly**
This performs a standard check to avoid some redundant calls. It also checks the signatures still exist.

### CODE REVIEW

**Comment by jheinen** [comment]
Thanks for the PR.

Why do you include `polyline` and `axes` in your `_precompile()` script? Maybe I didn't quite understand the point behind the patch, but these two functions produce output.

**Comment by sjkelly** [comment]
`polyline` and `axes` were in the original file so I preserved them: https://github.com/jheinen/GR.jl/pull/451/files#diff-7bd6c400cb5e7e66d9e2b4b11236ac0a15dea9293742c88f4cb31388602c2bcdL4362-L4363

In general `precompiles` don't actually execute. In the typical use case they store inference information. If they are added to a sysimage they will also have native code.

**Comment by jheinen** [comment]
I removed any output functions in `precompile()`. Does this still work (for you) as expected?

**Comment by sjkelly** [comment]
I will have to re-time TTFP. I am not sure what you mean about "output functions" is your concern that output will happen during precompile?

**Comment by sjkelly** [comment]
Also with my other PRs it is possible this list can be bigger if so desired.

**Pull request merged**
